version: '3.8'
services:
  mongo-main:
    image: mongo:7
    container_name: mongo-main
    ports:
      - "27017:27017"
    volumes:
      - local-db-data:/data/db

  mongo-test:
    image: mongo:7
    container_name: mongo-test
    ports:
      - "27018:27017"
  
volumes:
  local-db-data: