version = 0.1
[default.deploy.parameters]
stack_name = "python-fastapi-lambda-example-stack"
resolve_s3 = true
s3_prefix = "python-fastapi-lambda-example-stack"
region = "eu-west-3"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
